demos/shbreakout.py: Explode 3 Bricks per Collision, no longer just 1
demo doing this much damage

           ■■■■■   ■   ■■   ■■■■■■■■■■■■■■   ■   ■■   ■■■■■   ■■■■■■■     ■     ■■■
     ■■      ■■■     ■         ■■■■■■■■      ■■■■   ■■■■■■   ■■■■■■           ■■■
       ■■        ■■■   ■     ■■■■■■■       ■ ■■■■■■■   ■■   ■■■■■     ■
        ■■■        ■■■   ■     ■■      ■■■   ■■■■■■■■■■■■   ■■■     ■     ■■
     ■■   ■■■      ■■■■■   ■■   ■   ■■■■■■   ■■   ■■■■■■   ■■     ■     ■

demo my Python 3 here actually raising an Exception that it never could raise

    ...  echo_caps = (3 * [" "]) + caps[-3:]
    ...  echo_caps = echo_caps[-3:]
    358  echo = " ".join(echo_caps)

    Traceback (most recent call last):
      ...
      File ".../shbreakout.py", line 358, in board_draw
        echo = " ".join(echo_caps)
               ^^^^^^^^^^^^^^^^^^^
    TypeError: sequence item 2: expected str instance, NoneType found