bin/: Accept Code-Review, of all the Bin Py here, from MyPy at PyPi·Org
shrug off how wildly often this forces no adoption < Oct/2021 Python 3.10,
    because '-> str | None', etc, triggers
        TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

-- (commonly) --
-- bin/cal.py --
-- bin/mkdir.py --
-- bin/open.py --
-- bin/optionee/__main__.py --
-- bin/optionee/byo/byoargparse.py --
-- bin/optionee/byo/byotermios.py --
-- bin/pq.py --
-- demos/glass1.py --
-- demos/glass1000.py --
-- demos/last2lines.py --

mark each Sourcefile as:  code reviewed by People, Black, Flake8, & MyPy

add a MyPy Return Type Annotation to each Def

go with the 'bin/optionee/byo/byoargparse.py' solution
    to declaring types for a derived 'argparse.ArgumentParser' Class
        who can 'parser.parse_args_else' well

just to satisfy MyPy, even though no failing test found,
    split a global shared 'class Main' out from a top-level 'def main() -> None:'

don't declare a typing.Union to stress the Caller, do split apart:
    def subprocess_run_stdout_bytes(..., errors) -> bytes|str:
        def subprocess_run_stdout_bytes(shline) -> bytes:
        def subprocess_run_stdout_surrogateescape(shline) -> str:

talk up the Lisp-ish Types
    Graf = list[str]
    Grid = list[list[str]]

-- Makefile --

'grep -nR' over 'grep -n', so we get the line-number's of
    the Def's seemingly lacking MyPy Return Type Annotations

grow to cover all of:  grep -nR '^ *def '
    no longer just:  grep -nR '^def '

grow to cover all of:  bin/*.py
    no longer just:  bin/optionee bin/pq.py

-- bin/byotools.py --

just to satisfy MyPy, even though no failing test found,
    separately assert '.__file__' of Module of Func is truthy, when it does exist

and match the looseness of MyPy,
    by not separately asserting that '.__file__' of Module exists,
        even though it doesn't in places such as:  import sys

stop holding a place for someday implementing ', keepends=True'
    inside of:  def str_splitgrafs

-- bin/ls.py --

drop the examples not now implemented

start tracking the dream of implementing:  ls.py -AdhlF -rt ...

do explicitly 'return None' when returning ' -> bool | None:'

-- bin/mv.py --

simplify Typing down to falsey-or-truthy list[str]
    from list[str] | None

-- bin/optionee/byo/byotty.py --

simplify Typing down to a Class|Instance Attribute declaration
    +    tcgetattr: list[int | list[bytes | int]] | None
    -        self.tcgetattr: list[int | list[bytes | int]] | None

-- bin/p --

pick the Modules surfaced into Discovery via
    sorted(_[0] for _  in sys.modules.items() if not hasattr(_[-1], "__file__"))
namely
    atexit builtins errno marshal posix pwd sys

also deprecate:  pyexpat

-- bin/pwd_.py --
-- bin/time_.py --

index the common Sh Verbs as best effort,
    while declining to collide with:  import pwd, time

-- bin/vi.py --

settle into declaring 'def exit' as loosely as
    def __exit__(self, *exc_info) -> bool | None:
so that MyPy lets us stack these,
    without pre-commit'ing the lower layers to -> None:

accept the MyPy shove to assert no TypeError before asserting no IndexError at:
    + assert chars_key, repr(chars_key)
      assert chars_key in "0123456789", repr(chars_key)

accept the MyPy shove into more correct-at-a-glance,
    by way of more explicit local Asserts, when our Code implies they must be,
        assert Bytes | None is Bytes not None
        assert Str | None is Str not None

accept the MyPy --disallow-redefinition default
    when it surfaces the arbitrary placement of mutable/ immutable typing more loudly
        + old_peeks_bytearray = enough_holds[len(peeks) :]
        + old_peeks = bytes(old_peeks_bytearray)

settle into declaring 'def kbhit' as narrowly as '-> bool',
    so as to duck out of the arcane Typing puzzles of 'select.select',
        although this makes 'def kbhit' a less transparent wrapper of 'select.select'

accept the MyPy shove to assert no TypeError before slicing at:
    + assert m1, (m1, bytes_)
      start_seq = m1.string[m1.start() : m1.end()]

accept the MyPy shove for explicit
    + tcgetattr: list[int | list[bytes | int]] | None